#!/usr/bin/env python3
"""Build the case study index and the More cases list from cases.json.

cases.json is the one list of case studies. Run this after adding or editing a case:

    python3 tools/build_cases.py

It rewrites two generated blocks, each between BEGIN/END markers:
  - case-studies.html: the topic sections and their cards (plain HTML, so the index
    works with JavaScript off and is readable by search engines)
  - app.js: the CASES list the More cases picker chooses from
  - index.html: the featured strip (cases marked "featured": true, at most three)
Nothing outside the markers is touched. Within a topic, newest cases come first.
"""
import html, json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "cases.json").read_text())
topics = {t["id"]: t["name"] for t in data["topics"]}

def esc(s):
    return html.escape(s, quote=True)

# every case must point at a page that exists, under a known topic
for c in data["cases"]:
    if c["topic"] not in topics:
        sys.exit(f"unknown topic {c['topic']!r} on {c['slug']}")
    if not (ROOT / f"{c['slug']}.html").exists():
        sys.exit(f"missing page {c['slug']}.html")

def by_topic(tid):
    cs = [c for c in data["cases"] if c["topic"] == tid]
    return sorted(cs, key=lambda c: c["added"], reverse=True)

def card(c, with_topic=False):
    kicker = f'{esc(topics[c["topic"]])} · {esc(c["client"])}' if with_topic else esc(c["client"])
    return (f'      <a class="cx" href="{c["slug"]}.html" data-topic="{c["topic"]}">\n'
            f'        <span class="cx-k">{kicker}</span>\n'
            f'        <span class="cx-t">{esc(c["title"])}</span>\n'
            f'        <span class="cx-l">{esc(c["line"])}</span>\n'
            f'        <span class="cx-n">{esc(c["number"])}</span>\n'
            f'      </a>')

sections = []
for t in data["topics"]:
    cs = by_topic(t["id"])
    if not cs:
        continue
    sections.append(
        f'  <section class="cx-sec" id="{t["id"]}" data-topic="{t["id"]}" data-reveal>\n'
        f'    <h2 class="section-label">{esc(t["name"])} <span class="cx-count">{len(cs)}</span></h2>\n'
        f'    <div class="cx-grid">\n' + "\n".join(card(c) for c in cs) + "\n    </div>\n  </section>")
index_block = "\n\n".join(sections)

registry = ",\n".join(
    "      {url:%s, title:%s, topic:%s}" % (json.dumps(c["slug"] + ".html"), json.dumps(c["title"]),
                                           json.dumps(topics[c["topic"]]))
    for t in data["topics"] for c in by_topic(t["id"]))

def splice(path, begin, end, block):
    p = ROOT / path
    s = p.read_text()
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if not pat.search(s):
        sys.exit(f"markers not found in {path}")
    p.write_text(pat.sub(lambda m: f"{begin}\n{block}\n{end}", s))

splice("case-studies.html", "<!-- BEGIN cases (generated by tools/build_cases.py) -->",
       "<!-- END cases -->", index_block)
splice("app.js", "/* BEGIN cases (generated by tools/build_cases.py) */",
       "/* END cases */", registry)
featured = [c for c in data["cases"] if c.get("featured")]
if len(featured) > 3:
    sys.exit("at most three cases can be featured")
featured_block = '    <div class="cx-grid">\n' + "\n".join(card(c, with_topic=True) for c in featured) + "\n    </div>"
splice("index.html", "<!-- BEGIN featured (generated by tools/build_cases.py) -->",
       "<!-- END featured -->", featured_block)

print(f"built {len(data['cases'])} cases across {len(sections)} topics, {len(featured)} featured")
